[package]
name = "int-enum"
version = "0.5.0"
authors = ["Juici <juicy66173@gmail.com>"]
description = "A derive macro for conversion between integer and enum types."
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.63"

documentation = "https://docs.rs/int-enum"
repository = "https://github.com/Juici/int-enum-rs"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
proc-macro2-diagnostics = "0.10"
quote = "1"
syn = "2"

[dev-dependencies]
rustversion = "1"
trybuild = "1"

[build-dependencies]
version_check = "0.9"
